Feature:Operation for getting trainer profile positive scenario with valid input data and negative scenario with invalid data

  Scenario: Getting a trainer profile with success output
    Given a user sends the get request to the specified url for trainer getting profile with valid username and password
    When the system checks the credentials and retrieving trainer information and returns status code 200
    Then the system should respond with TrainerProfileResponse generated by the system


  Scenario: Getting a trainer profile with failed output
    Given a user sends the get request to the specified url for trainer getting profile, but input invalid username
    When the system checks the credentials and failed to retrieve trainer info and throws an exception
    Then the system should respond with the status code 400 the bad request the username not found in the database