Feature:Operation for trainer register positive scenario with valid input data and negative scenario with invalid data

  Scenario: Register a Trainer with success output
    Given a user sends the post request to the specified url for trainer register with valid data
    When the system validates the input and saves the trainer and returns status code 200
    Then the system should respond with RegistrationResponse generated by the system


  Scenario: Register a Trainee with failed output
    Given a user sends the post request to the specified url for trainer register with specialization id 6
    When the system validates the requests and failed to save the trainer due to specialization id over max value
    Then the system should respond with the status code 400 the bad request wrong specialization id