Feature: trainee register positive scenario with valid input data and negative scenario with invalid data

  Scenario: Register a Trainee with success output
    Given a user sends the post request to the specified url with valid data
    When the system validates the input information and saves the trainee and returns status code 200
    Then the system should respond with a successful registration response with login and password generated by the system


  Scenario: Register a Trainee with failed output
    Given a user sends the post request to the specified url with empty first name data
    When the system validates the requests and failed to save the trainee
    Then the system should respond with the bad request the status code 400
