package stepDef.trainer;

import com.epam.gym.dto.RegistrationResponse;
import com.epam.gym.dto.trainer.TrainerRegisterRequest;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;


public class TrainerRegisterSuccessStepDefinition {

    @Autowired
    private RestTemplate restTemplate;
    @LocalServerPort
    private String port;
    private TrainerRegisterRequest trainerRegisterRequest;
    private ResponseEntity<RegistrationResponse> registrationResponseResponseEntity;
    private RegistrationResponse registrationResponse;

    @Given("a user sends the post request to the specified url for trainer register with valid data")
    public void a_user_send_the_post_request_to_the_url_for_trainer_register() {
        trainerRegisterRequest = new TrainerRegisterRequest();
        trainerRegisterRequest.setFirstName("Bill");
        trainerRegisterRequest.setLastName("Hugo");
        trainerRegisterRequest.setSpecializationId(5L);
        HttpEntity<TrainerRegisterRequest> requestEntity = new HttpEntity<>(trainerRegisterRequest);
        registrationResponseResponseEntity = restTemplate.exchange("http://localhost:"+ port +"/trainers",
                HttpMethod.POST,
                requestEntity,
                RegistrationResponse.class
                );

    }
    @When("the system validates the input and saves the trainer and returns status code {int}")
    public void the_system_saves_the_trainer_and_returns_200_ok(int expected) {
        assertEquals(HttpStatus.valueOf(expected), registrationResponseResponseEntity.getStatusCode());
    }

    @Then("the system should respond with RegistrationResponse generated by the system")
    public void the_system_should_respond_with_registrationResponse() {
      this.registrationResponse = registrationResponseResponseEntity.getBody();
      assertNotNull(registrationResponse);
      assertNotNull(registrationResponse.getLogin());
      assertNotNull(registrationResponse.getPassword());
    }

}
